config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :blog_posts do
    resource :cover_image, only: [:destroy], module: :blog_posts
  end

  # Defines the root path route ("/")
  root "blog_posts#index"

  get '/search_blogpost', to: 'search#search_blogpost'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post_category.rb
class BlogPostCategory < ApplicationRecord
  belongs_to :blogpost
  belongs_to :category
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  has_one_attached :cover_image
  has_rich_text :content
  has_many :blog_post_categories, class_name: "BlogPostCategory"
  has_many :categories, through: :blog_post_categories
  validates :title, presence: true
  validates :content, presence: true


  scope :sorted, ->{ order(arel_table[:published_at].desc.nulls_first).order(updated_at: :desc)}
  scope :draft, -> { where(published_at: nil)}
  scope :published, -> { where("published_at <= ?", Time.current) }
  scope :scheduled, -> { where("published_at > ?", Time.current) }

  def draft?
    published_at.nil?
  end

  def published?
    published_at? && published_at <= Time.current
  end

  def scheduled?
    published_at? && published_at > Time.current
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :blog_post_categories, class_name: "BlogPostCategory"
  has_many :blogposts, through: :blog_post_categories
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
end

app/controllers/blog_posts/cover_images_controller.rb
class BlogPosts::CoverImagesController < ApplicationController
  include ActionView::RecordIdentifier

  before_action :authenticate_user!
  before_action :set_blog_post

  def destroy
    @blog_post.cover_image.purge_later

    respond_to do |format|
      format.html {redirect_to edit_blog_post_path(@blog_post)}
      format.turbo_stream {render turbo_stream: turbo_stream.remove(dom_id(@blog_post, :cover_image))}
    end
  end

  def set_blog_post
    @blog_post = Blogpost.find(params[:blog_post_id])
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  def index
    @blog_posts = user_signed_in? ? Blogpost.sorted : Blogpost.published.sorted
    @pagy, @blog_posts = pagy(@blog_posts)
  rescue Pagy::OverflowError
    params[:page] = 1
    retry
  end

  def new
    @blog_post = Blogpost.new
  end

  def show
  end

  def create
    @blog_post = Blogpost.new(blog_post_params)
    if @blog_post.save
      redirect_to blog_post_url(@blog_post)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to blog_post_url(@blog_post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy
    redirect_to root_path
  end
  def blog_post_params
    params.require(:blogpost).permit(:title, :content, :published_at, :cover_image, category_ids: [])
  end

  def set_blog_post
    @blog_post = user_signed_in? ? Blogpost.find(params[:id]) : Blogpost.published.find(params[:id])
    begin
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end

  def authenticate_user!
    redirect_to new_user_session_path, alert: "You must be signed in" unless user_signed_in?
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search_blogpost
    @get_blogpost = user_signed_in? ?
                      Blogpost.where("title LIKE ?", "%#{params[:title]}%").sorted :
                      Blogpost.where("title LIKE ?", "%#{params[:title]}%").published.sorted
    puts @get_blogpost
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog_posts/_form.html.erb
<%= form_with model: @blog_post, url: (@blog_post.persisted? ? blog_post_path(@blog_post) : blog_posts_path),
               class: "bg-white shadow-md rounded px-auto pt-6 pb-6 mb-6 " do |form| %>
  <% if form.object.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4 px-3" role="alert">
      <% form.object.errors.full_messages.each do |message| %>
        <span class="block sm:inline"><%= message %></span>
      <% end %>
    </div>
  <% end %>
  <div class="mt-6 mb-4 py-2 px-3">
    <%= form.label :title, class: "block text-gray-700 text-sm font-bold " %>
    <%= form.text_field :title, class: "shadow appearance-none border rounded w-full px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mt-6 mb-4" %>
  </div>

  <div class="mt-6 mb-4 py-2 px-3">
    <%= form.label :cover_image, class: "block text-gray-700 text-sm font-bold mb-2" %>
    <% if @blog_post.cover_image.present? %>
      <div id="<%= dom_id(@blog_post, :cover_image) %>" class="mb-4">
        <%= image_tag @blog_post.cover_image, class: "w-1/3 mb-2"%>
        <%= link_to "Remove cover image", blog_post_cover_image_path(@blog_post),
                    data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-blue-500 hover:text-blue-800" %>
      </div>
    <% end %>
    <%= form.file_field :cover_image, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mt-6 mb-4" %>
  </div>

  <div class="mt-6 mb-4 py-2 px-3">
    <%= form.label :content, class: "block text-gray-700 text-sm font-bold mb-2 mt-6" %>
    <%= form.rich_text_area :content, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline mt-6 mb-4" %>
  </div>

  <div class="mt-6 mb-4 py-2 px-3">
    <%= form.label :published_at, class: "block text-gray-700 text-sm font-bold mb-2 mt-6" %>
    <%= form.datetime_select :published_at, include_blank: true, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline  mb-4" %>
  </div>

  <div class="flex inline mb-4 py-2 px-3">
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
      <div class="mb-2">
        <%= b.check_box  %>
        <%= b.label class: "mr-4" %>
      </div>
    <% end %>
  </div>

  <div class="flex mb-4 py-2 px-3">
  <%= form.submit class: " bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mb-6" %>
    </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1 class="mt-6"> Edit blog post</h1>

<%= form_with model: @blog_post, url: (@blog_post.persisted? ? blog_post_path(@blog_post) : blog_posts_path),
              class: "bg-white shadow-md rounded px-auto pt-6 pb-6 mb-6 " do |form| %>
  <% if form.object.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4 px-3" role="alert">
      <% form.object.errors.full_messages.each do |message| %>
        <span class="block sm:inline"><%= message %></span>
      <% end %>
    </div>
  <% end %>
  <%= render partial: "form", locals: {blogpost: @blog_post} %>

  <%= button_to "Delete", blog_post_path(@blog_post), method: :delete, data: {turbo_confirm: "Are you sure?"}, class: " bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-6 mb-6" %>
<% end %>

app/views/blog_posts/index.html.erb
<h1 class="mt-6">Welcome to my blog!</h1>
<% @blog_posts.each do |blog_post| %>
  <div class="p-4 mb-4 border rounded shadow mt-6">
    <% if blog_post.cover_image.present? %>
      <div class="w-1/2 h-1/4">
        <%= image_tag blog_post.cover_image, class: "mx-auto object-cover h-auto w-full" %>
      </div>
    <% end %>
    <h2>
      <%= link_to blog_post.title, blog_post_path(blog_post), class: "no-underline text-indigo-600"%>
    </h2>
    <% if blog_post.draft? %>
      <div class="p-2 mb-2 rounded bg-gray-100 text-gray-900">
        Draft
      </div>
    <% elsif blog_post.scheduled? %>
      <div class="p-2 mb-2 rounded bg-blue-100 text-blue-900">
        Scheduled
      </div>
    <% end %>
    <div class="flex space-x-2 mt-6">
      <% blog_post.categories.each do |category| %>
        <% if category.name == 'General' %>
          <div class="p-2 rounded bg-gray-100 text-gray-900 ml-2">
            <%= category.name %>
          </div>
        <% elsif category.name == 'Software' %>
          <div class="p-2 rounded bg-blue-100 text-blue-900 ml-2">
            <%= category.name %>
          </div>
        <% elsif category.name == 'News' %>
          <div class="p-2 rounded bg-indigo-600 text-white ml-2">
            <%= category.name %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
<% if @pagy.count > @pagy.items %>
  <div  class="my-16">
    <%==  pagy_nav(@pagy)%>
  </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1>Create new blog post!</h1>

<%= render partial: "form", locals: {blogpost: @blog_post} %>

app/views/blog_posts/show.html.erb
<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 border rounded shadow mt-6 mb-4">
  <%= link_to "Edit", edit_blog_post_path(@blog_post), class: "no-underline text-indigo-600 mt-6" if user_signed_in? %>

  <%= image_tag @blog_post.cover_image if @blog_post.cover_image.present? %>

  <h1 class="mt-4"><%= @blog_post.title %></h1>
  <div class="mt-4">
    <%= @blog_post.content %>
  </div>
  <div class="flex space-x-2 mt-6 p-4 ">
    <% @blog_post.categories.each do |category| %>
      <% if category.name == 'General' %>
        <div class="p-2 rounded bg-gray-100 text-gray- ml-2">
          <%= category.name %>
        </div>
      <% elsif category.name == 'Software' %>
        <div class="p-2 rounded bg-blue-100 text-blue-900 ml-2">
          <%= category.name %>
        </div>
      <% elsif category.name == 'News' %>
        <div class="p-2 rounded bg-indigo-600 text-white ml-2">
          <%= category.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogapp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body class="prose w-full mx-auto m-0 p-0">
<nav class="bg-blue-500 p-4 flex justify-between items-center w-full m-0 p-0">  <div>
    <a href="/" class="text-white text-lg font-bold no-underline">Blogapp</a>
  </div>
  <div>
    <% if user_signed_in?  %>
      <%= link_to "New blog post", new_blog_post_path, class: "text-white mr-4 no-underline" %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" %>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded mr-4 no-underline" %>
    <% end %>
  </div>
</nav>

<div class="mt-4">
  <% if notice %>
    <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Hey!</strong>
      <span class="block sm:inline"><%= notice %></span>
    </div>
  <% end %>

  <% if alert %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Alert!</strong>
      <span class="block sm:inline"><%= alert %></span>
    </div>
  <% end %>
</div>

<%= yield %>
</body>
</html>

app/views/search/search_blogpost.html.erb
<% if @get_blogpost.empty? %>
  <p> No bloposts with that name </p>
  <% else %>
<% @get_blogpost.each do |blog_post| %>
  <div class="p-4 mb-4 border rounded shadow mt-6">
    <% if blog_post.cover_image.present? %>
      <div class="w-1/2 h-1/4">
        <%= image_tag blog_post.cover_image, class: "mx-auto object-cover h-auto w-full" %>
      </div>
    <% end %>
    <h2>
      <%= link_to blog_post.title, blog_post_path(blog_post), class: "no-underline text-indigo-600"%>
    </h2>
    <% if blog_post.draft? %>
      <div class="p-2 mb-2 rounded bg-gray-100 text-gray-900">
        Draft
      </div>
    <% elsif blog_post.scheduled? %>
      <div class="p-2 mb-2 rounded bg-blue-100 text-blue-900">
        Scheduled
      </div>
    <% end %>
    <div class="flex space-x-2 mt-6">
      <% blog_post.categories.each do |category| %>
        <% if category.name == 'General' %>
          <div class="p-2 rounded bg-gray-100 text-gray-900 ml-2">
            <%= category.name %>
          </div>
        <% elsif category.name == 'Software' %>
          <div class="p-2 rounded bg-blue-100 text-blue-900 ml-2">
            <%= category.name %>
          </div>
        <% elsif category.name == 'News' %>
          <div class="p-2 rounded bg-indigo-600 text-white ml-2">
            <%= category.name %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
<% end  %>